# Generated by Django 4.2.18 on 2025-02-04 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pypackages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wheel',
            name='author',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='wheel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wheel',
            name='file_path',
            field=models.FileField(blank=True, null=True, upload_to='upload/'),
        ),
        migrations.AddField(
            model_name='wheel',
            name='keywords',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wheel',
            name='license',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='wheel',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
