# Generated by Django 4.2.18 on 2025-02-05 13:28

from django.db import migrations, models
import pypackages.models


class Migration(migrations.Migration):

    dependencies = [
        ('pypackages', '0002_wheel_author_wheel_description_wheel_file_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wheel',
            name='whl_file',
            field=models.FileField(blank=True, null=True, upload_to=pypackages.models.learning_data_path),
        ),
    ]
