# Generated by Django 4.2.18 on 2025-02-05 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pypackages', '0004_remove_wheel_file_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wheel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
