# Generated by Django 4.2.18 on 2025-02-05 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pypackages', '0006_alter_wheel_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wheel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
