services:
    nginx:
        container_name: nginx
        image: docker-nginx:1.26
        volumes:
            - ./static:/app/static
            - ./uploads:/app/uploads
        ports:
            - 80:80
        depends_on:
          - web
    web:
        container_name: web
        image: docker-project:latest
        entrypoint: /app/entrypoint.sh
        volumes:
            - ./static:/app/static
            - ./uploads:/app/uploads
        ports:
            - :8000